[package]
name = "x"

edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
indent = "0.1.1"
pretty_assertions = "1.4.1"
serde = "1.0"
serde_json = "1.0"
styled = "0.2.0"
unindent = "0.2.4"
